import torch

a = torch.randint(1, 5, (2, 3))
b = torch.randint(1, 5, (2, 3))
print(a)
print(b)

print(a + b)
print(a - b)
# print(a * b)
# print(a / b)
# print(a ** b)
# print(a % b)
# print(a // b)
# print(a > b)
# print(a < b)
# print(a >= b)
# print(a <= b)
# print(a == b)
# print(a != b)
# print(a & b)
# print(a | b)
# print(a ^ b)
# print(a & b | a ^ b)